SUBDIR = ./build
SENDUCITOCLI = ./senducitocli
RUNQOS = ./runCommand
TR143 = ./TR143
ONEAGENT_MON = ./oneagent_mon
TRNOTIFYD = ./tr_notifyd
TEST = ./test
MAKE = make
subsystem:
	cd $(SUBDIR) && $(MAKE)
	cd $(SENDUCITOCLI) && $(MAKE)
	cd $(ONEAGENT_MON) && $(MAKE)
	cd $(RUNQOS) && $(MAKE)
	cd $(TR143) && $(MAKE)
	cd $(TRNOTIFYD) && $(MAKE)
	cd $(TEST) && $(MAKE)
